"""Pydantic models for Event Radar pipeline."""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, Field

EventCategory = Literal[
    "earnings",
    "economic_data",
    "fed",
    "13f_filing",
    "conference",
    "release",
    "regulatory",
    "other",
]

EventSector = Literal[
    "ai", "semiconductors", "ai_infrastructure", "power", "energy", "precious_metals"
]

EventRegion = Literal["US", "JP", "SG", "HK", "global"]

EventCadence = Literal["annual", "biannual", "quarterly", "monthly", "irregular"]


class CalendarEvent(BaseModel):
    """A market-relevant event extracted from any source."""

    title: str
    description: str | None = None
    event_date: date
    event_end_date: date | None = None
    category: EventCategory
    sector: EventSector | None = None
    region: list[EventRegion]
    tickers: list[str] = Field(default_factory=list)
    importance: int = Field(ge=1, le=10)
    importance_reasoning: str | None = None
    source_urls: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)


class CalendarEventRow(BaseModel):
    """A calendar event as stored in the database (includes DB-generated fields)."""

    id: int
    title: str
    description: str | None = None
    event_date: date
    event_end_date: date | None = None
    category: EventCategory
    sector: EventSector | None = None
    region: list[str]
    tickers: list[str]
    importance: int
    importance_reasoning: str | None = None
    source_urls: list[str]
    confidence: float
    discovered_at: datetime
    updated_at: datetime
    title_hash: str


class EventPattern(BaseModel):
    """A learned recurring event pattern."""

    id: int | None = None
    event_name: str
    organizer: str | None = None
    category: EventCategory
    sector: EventSector | None = None
    cadence: EventCadence
    typical_month: int | None = None
    typical_region: list[EventRegion] | None = None
    typical_tickers: list[str] | None = None
    last_occurrence: date | None = None
    next_expected: date | None = None
    times_seen: int = 1


class SearchQuery(BaseModel):
    """A search query generated by the LLM query planner."""

    query: str
    rationale: str
    target_region: EventRegion | None = None
    target_sector: EventSector | None = None


class ExtractedEvents(BaseModel):
    """Output from the LLM event extractor."""

    events: list[CalendarEvent]


# ─────────────────────────────────────────────────────────────
# LLM Digest Synthesis Models
# ─────────────────────────────────────────────────────────────

DigestCategory = Literal[
    "macro",
    "tech",
    "corporate",
    "sector",
    "regulatory",
    "earnings",
    "13f_filing",
    "fed",
]


class MarketSnapshot(BaseModel):
    """Market data context for yesterday's session."""

    summary: str
    equities: str
    rates_fx: str
    commodities: str
    volatility: str
    sector_performance: str


class Actionable(BaseModel):
    """A specific trading actionable from yesterday's events."""

    action: str
    rationale: str
    tickers: list[str]
    direction: Literal["long", "short", "hedge", "watch"]
    timeframe: Literal["today", "this_week", "swing"]


class YesterdayTheme(BaseModel):
    """A theme from yesterday's events analysis."""

    title: str
    category: DigestCategory
    sentiment: Literal["bullish", "bearish", "neutral"]
    source: Literal["calendar", "surprise", "analysis"]
    outcome: str
    analysis: str
    key_events: list[str]
    tickers: list[str]
    market_reaction: str


class YesterdayBriefAnalysis(BaseModel):
    """LLM analysis of yesterday's events."""

    headline: str
    market_snapshot: MarketSnapshot
    themes: list[YesterdayTheme]
    synthesis: str
    actionables: list[Actionable]
    risk_radar: list[str]
    top_movers: list[str]


class SubAnalysis(BaseModel):
    """Intermediate output from a yesterday brief sub-analyzer."""

    themes: list[YesterdayTheme]
    key_takeaways: list[str]
    tickers_affected: list[str]
