"""Sentiment lexicon data: word scores, modifiers, and finance-specific terms.

This module contains hardcoded lexicon constants for fast access. The full lexicons
are stored in data/lexicons/*.json and can be loaded for extensibility.
"""

from typing import Final

# =============================================================================
# SENTIMENT MODIFIERS (VADER-inspired rules)
# =============================================================================

# Booster words increase sentiment intensity
BOOSTERS: Final[dict[str, float]] = {
    "absolutely": 0.293,
    "amazingly": 0.293,
    "awfully": 0.293,
    "completely": 0.293,
    "considerably": 0.293,
    "decidedly": 0.293,
    "deeply": 0.293,
    "effing": 0.293,
    "enormously": 0.293,
    "entirely": 0.293,
    "especially": 0.293,
    "exceptionally": 0.293,
    "extremely": 0.293,
    "fabulously": 0.293,
    "flipping": 0.293,
    "flippin": 0.293,
    "freaking": 0.293,
    "frickin": 0.293,
    "fricking": 0.293,
    "friggin": 0.293,
    "frigging": 0.293,
    "fucking": 0.293,
    "fuckin": 0.293,
    "fully": 0.293,
    "greatly": 0.293,
    "hella": 0.293,
    "highly": 0.293,
    "hugely": 0.293,
    "incredibly": 0.293,
    "intensely": 0.293,
    "majorly": 0.293,
    "more": 0.293,
    "most": 0.293,
    "particularly": 0.293,
    "purely": 0.293,
    "quite": 0.293,
    "really": 0.293,
    "remarkably": 0.293,
    "so": 0.293,
    "substantially": 0.293,
    "super": 0.293,
    "supremely": 0.293,
    "thoroughly": 0.293,
    "totally": 0.293,
    "tremendously": 0.293,
    "truly": 0.293,
    "uber": 0.293,
    "unbelievably": 0.293,
    "unusually": 0.293,
    "utterly": 0.293,
    "very": 0.293,
}

# Dampener words decrease sentiment intensity
DAMPENERS: Final[dict[str, float]] = {
    "almost": -0.293,
    "barely": -0.293,
    "hardly": -0.293,
    "just enough": -0.293,
    "kind of": -0.293,
    "kinda": -0.293,
    "kindof": -0.293,
    "kind-of": -0.293,
    "less": -0.293,
    "little": -0.293,
    "marginally": -0.293,
    "occasionally": -0.293,
    "partly": -0.293,
    "scarcely": -0.293,
    "slightly": -0.293,
    "somewhat": -0.293,
    "sort of": -0.293,
    "sorta": -0.293,
    "sortof": -0.293,
    "sort-of": -0.293,
}

# Negation words flip sentiment polarity
NEGATIONS: Final[frozenset[str]] = frozenset(
    {
        "aint",
        "arent",
        "cannot",
        "cant",
        "couldnt",
        "darent",
        "didnt",
        "doesnt",
        "dont",
        "hadnt",
        "hasnt",
        "havent",
        "isnt",
        "mightnt",
        "mustnt",
        "neednt",
        "never",
        "no",
        "nobody",
        "none",
        "nope",
        "nor",
        "not",
        "nothing",
        "nowhere",
        "oughtnt",
        "shant",
        "shouldnt",
        "uhuh",
        "uh-uh",
        "wasnt",
        "werent",
        "without",
        "wont",
        "wouldnt",
        "rarely",
        "seldom",
        "neither",
    }
)

# Special conjunctions that affect clause weighting
SPECIAL_CONJUNCTIONS: Final[dict[str, float]] = {
    "but": 1.5,  # Post-but clause weighted higher
    "however": 1.3,
    "yet": 1.3,
    "although": 0.8,  # Pre-clause downweighted
    "though": 0.8,
    "despite": 0.8,
}

# =============================================================================
# MODIFIER CONSTANTS
# =============================================================================

# Multiplier for negation (VADER uses -0.74)
NEGATION_SCALAR: Final[float] = -0.74

# Bonus for ALL CAPS emphasis
CAPS_EMPHASIS: Final[float] = 0.733

# Punctuation bonuses
EXCLAMATION_BONUS: Final[float] = 0.292
QUESTION_BONUS: Final[float] = 0.18

# Maximum exclamation marks to count
MAX_EXCLAMATION: Final[int] = 4

# Normalization alpha (for compound score calculation)
NORMALIZATION_ALPHA: Final[float] = 15.0

# =============================================================================
# BASE LEXICON (curated subset of common sentiment words)
# =============================================================================

BASE_LEXICON: Final[dict[str, float]] = {
    # Strong positive (3.0+)
    "amazing": 3.1,
    "awesome": 3.0,
    "excellent": 3.2,
    "fantastic": 3.0,
    "great": 3.1,
    "incredible": 3.0,
    "outstanding": 3.2,
    "perfect": 3.0,
    "superb": 3.1,
    "wonderful": 3.0,
    "brilliant": 3.0,
    "extraordinary": 3.1,
    "magnificent": 3.0,
    "phenomenal": 3.1,
    "spectacular": 3.0,
    "terrific": 2.9,
    "tremendous": 2.8,
    # Moderate positive (2.0-2.9)
    "beautiful": 2.5,
    "delightful": 2.5,
    "enjoyable": 2.3,
    "fabulous": 2.7,
    "favorable": 2.0,
    "fortunate": 2.2,
    "fun": 2.2,
    "glad": 2.0,
    "good": 1.9,
    "happy": 2.5,
    "impressive": 2.4,
    "lovely": 2.3,
    "nice": 1.8,
    "pleasant": 2.0,
    "pleased": 2.1,
    "positive": 2.0,
    "satisfied": 2.0,
    "successful": 2.3,
    "thrilled": 2.7,
    # Weak positive (1.0-1.9)
    "acceptable": 1.2,
    "adequate": 1.0,
    "agree": 1.3,
    "better": 1.5,
    "bonus": 1.5,
    "cool": 1.5,
    "decent": 1.2,
    "fine": 1.0,
    "helpful": 1.5,
    "interesting": 1.3,
    "like": 1.5,
    "okay": 0.8,
    "ok": 0.8,
    "promising": 1.6,
    "solid": 1.4,
    "thanks": 1.4,
    "useful": 1.3,
    "well": 1.2,
    "win": 2.0,
    "winning": 2.2,
    "worth": 1.3,
    # Strong negative (-3.0 or less)
    "abysmal": -3.2,
    "appalling": -3.0,
    "atrocious": -3.2,
    "awful": -3.1,
    "dreadful": -3.0,
    "horrible": -3.1,
    "horrendous": -3.2,
    "terrible": -3.2,
    "tragic": -3.0,
    "worst": -3.5,
    "catastrophic": -3.3,
    "devastating": -3.1,
    "disastrous": -3.2,
    "disgraceful": -3.0,
    "disgusting": -3.0,
    "horrid": -3.0,
    "miserable": -2.9,
    "pathetic": -2.9,
    "repulsive": -3.0,
    "garbage": -3.0,
    "trash": -2.8,
    "crap": -2.5,
    "rubbish": -2.5,
    # Moderate negative (-2.0 to -2.9)
    "angry": -2.5,
    "annoying": -2.2,
    "bad": -2.5,
    "disappointing": -2.3,
    "disappointed": -2.3,
    "dumb": -2.2,
    "fail": -2.5,
    "failed": -2.5,
    "failing": -2.3,
    "frustrating": -2.3,
    "hate": -2.8,
    "hated": -2.8,
    "hating": -2.6,
    "inferior": -2.1,
    "lame": -2.0,
    "lousy": -2.3,
    "negative": -2.0,
    "pain": -2.2,
    "painful": -2.3,
    "poor": -2.2,
    "sad": -2.3,
    "sucks": -2.5,
    "suck": -2.5,
    "stupid": -2.5,
    "ugly": -2.2,
    "unhappy": -2.3,
    "useless": -2.5,
    "weak": -2.0,
    "wrong": -2.0,
    # Weak negative (-1.0 to -1.9)
    "boring": -1.5,
    "concerned": -1.3,
    "confusing": -1.4,
    "difficult": -1.2,
    "dislike": -1.8,
    "doubt": -1.5,
    "doubtful": -1.6,
    "dull": -1.3,
    "hard": -1.0,
    "lacking": -1.3,
    "limited": -1.2,
    "loss": -1.8,
    "lost": -1.5,
    "mediocre": -1.5,
    "meh": -1.2,
    "miss": -1.3,
    "missed": -1.4,
    "missing": -1.2,
    "ordinary": -0.8,
    "problem": -1.5,
    "risk": -1.3,
    "risky": -1.5,
    "slow": -1.2,
    "struggle": -1.5,
    "struggling": -1.6,
    "tough": -1.2,
    "trouble": -1.6,
    "uncertain": -1.4,
    "unclear": -1.3,
    "unfortunate": -1.8,
    "worried": -1.5,
    "worry": -1.4,
}

# =============================================================================
# FINANCE-SPECIFIC LEXICON
# =============================================================================

FINANCE_LEXICON: Final[dict[str, float]] = {
    # Strong bullish (2.5+)
    "bullish": 2.5,
    "moon": 2.8,
    "mooning": 3.0,
    "moonshot": 3.0,
    "rip": 2.2,
    "ripping": 2.5,
    "breakout": 2.3,
    "breakouts": 2.3,
    "ath": 2.5,  # All-time high
    "rally": 2.3,
    "rallying": 2.5,
    "soar": 2.5,
    "soaring": 2.7,
    "surge": 2.3,
    "surging": 2.5,
    "rocket": 2.5,
    "rocketing": 2.7,
    "skyrocket": 2.8,
    "skyrocketing": 3.0,
    "explode": 2.3,
    "exploding": 2.5,
    "parabolic": 2.8,
    "squeeze": 2.5,
    "squeezing": 2.7,
    "gamma": 1.5,  # Gamma squeeze context
    "outperform": 2.0,
    "outperforming": 2.2,
    "upgrade": 2.0,
    "upgraded": 2.2,
    "beat": 1.8,
    "beats": 1.8,
    "beating": 2.0,
    "exceeded": 2.0,
    "exceeds": 1.8,
    "blowout": 2.3,
    "profit": 1.8,
    "profits": 1.8,
    "profitable": 2.0,
    "gains": 2.0,
    "gain": 1.8,
    "winning": 2.0,
    "winner": 2.0,
    "winners": 2.0,
    "tendies": 2.5,  # WSB slang for gains
    "printing": 2.3,  # "Calls printing"
    "print": 2.0,
    "lambo": 2.5,  # "wen lambo"
    "yacht": 2.3,
    "rich": 2.0,
    # Moderate bullish (1.5-2.4)
    "buy": 1.5,
    "buying": 1.6,
    "bought": 1.4,
    "long": 1.3,
    "longing": 1.5,
    "calls": 1.5,
    "call": 1.3,
    "accumulate": 1.8,
    "accumulating": 2.0,
    "hodl": 1.8,
    "hodling": 2.0,
    "hold": 1.2,
    "holding": 1.3,
    "diamond": 2.0,  # Diamond hands
    "growth": 1.6,
    "growing": 1.8,
    "recover": 1.6,
    "recovering": 1.8,
    "recovery": 1.8,
    "rebound": 1.8,
    "rebounding": 2.0,
    "upside": 1.8,
    "support": 1.5,
    "bounce": 1.6,
    "bouncing": 1.8,
    "undervalued": 1.8,
    "cheap": 1.5,
    "discount": 1.6,
    "opportunity": 1.5,
    "dip": 1.2,  # "Buy the dip"
    "btfd": 1.8,  # Buy the fucking dip
    # Strong bearish (-2.5 or less)
    "bearish": -2.5,
    "dump": -2.5,
    "dumping": -2.7,
    "dumped": -2.5,
    "crash": -3.0,
    "crashing": -3.2,
    "crashed": -3.0,
    "rug": -3.5,
    "rugged": -3.5,
    "rugpull": -3.5,
    "scam": -3.0,
    "scammed": -3.2,
    "fraud": -3.0,
    "fraudulent": -3.2,
    "ponzi": -3.0,
    "collapse": -3.0,
    "collapsing": -3.2,
    "collapsed": -3.0,
    "plunge": -2.8,
    "plunging": -3.0,
    "plummit": -2.8,
    "plummeting": -3.0,
    "tank": -2.5,
    "tanking": -2.7,
    "tanked": -2.5,
    "drill": -2.3,
    "drilling": -2.5,
    "drilled": -2.3,
    "bloodbath": -3.0,
    "massacre": -2.8,
    "carnage": -2.8,
    "rekt": -3.0,
    "wrecked": -2.8,
    "destroyed": -2.8,
    "obliterated": -3.0,
    "guh": -3.5,  # WSB loss exclamation
    "worthless": -3.0,
    "expire": -2.0,
    "expired": -2.5,  # Options expired worthless
    "bagholding": -2.5,
    "bagholder": -2.5,
    "bagholders": -2.5,
    # Moderate bearish (-1.5 to -2.4)
    "sell": -1.5,
    "selling": -1.6,
    "sold": -1.4,
    "short": -1.5,
    "shorting": -1.7,
    "shorted": -1.5,
    "puts": -1.5,
    "put": -1.3,
    "downgrade": -2.0,
    "downgraded": -2.2,
    "miss": -1.8,
    "missed": -1.8,
    "missing": -1.6,
    "loss": -2.0,
    "losses": -2.2,
    "losing": -2.0,
    "loser": -2.0,
    "losers": -2.0,
    "overvalued": -1.8,
    "expensive": -1.5,
    "bubble": -2.0,
    "resistance": -1.3,
    "breakdown": -1.8,
    "downside": -1.8,
    "decline": -1.8,
    "declining": -2.0,
    "drop": -1.6,
    "dropping": -1.8,
    "fell": -1.6,
    "falling": -1.8,
    "fall": -1.5,
    "red": -1.5,
    "bleed": -2.0,
    "bleeding": -2.2,
    "paper": -1.5,  # Paper hands
    "fud": -1.8,  # Fear, uncertainty, doubt
    "fear": -1.8,
    "panic": -2.2,
    "panicking": -2.5,
    # Neutral but important (context-dependent, slight bias)
    "volatile": -0.8,
    "volatility": -0.8,
    "uncertainty": -1.0,
    "risk": -1.0,
    "risky": -1.2,
    "sideways": -0.3,
    "flat": -0.3,
    "consolidating": 0.3,
    "consolidation": 0.3,
    "correction": -0.8,
    "pullback": -0.5,
    # Macro/news terms (slight directional bias)
    "hawkish": -0.8,  # Usually bearish for growth
    "dovish": 0.8,  # Usually bullish for growth
    "inflation": -0.8,
    "recession": -1.5,
    "stagflation": -1.8,
    "default": -2.0,
    "bankruptcy": -2.5,
    "layoffs": -1.8,
    "layoff": -1.8,
    "fired": -1.5,
    "hiring": 1.2,
    "expansion": 1.5,
    "stimulus": 1.5,
    "easing": 1.2,
    "tightening": -0.8,
    "cut": 0.8,  # Rate cut usually bullish
    "hike": -0.8,  # Rate hike usually bearish
}

# =============================================================================
# EMOJI LEXICON
# =============================================================================

EMOJI_LEXICON: Final[dict[str, float]] = {
    # Strong bullish
    "🚀": 2.5,
    "🌙": 2.0,
    "🌕": 2.0,
    "💎": 2.0,
    "🙌": 1.5,
    "💪": 1.5,
    "🔥": 1.5,  # Context-dependent but usually positive
    "📈": 2.0,
    "💹": 2.0,
    "🤑": 2.0,
    "💰": 1.8,
    "💵": 1.5,
    "💸": 1.0,  # Can be losing money
    "🎯": 1.5,
    "✅": 1.5,
    "👍": 1.5,
    "👆": 1.2,
    "⬆️": 1.5,
    "🟢": 1.8,
    "💚": 1.5,
    "🐂": 2.0,  # Bull
    "🦍": 1.5,  # Ape (WSB)
    "🦧": 1.5,
    "🍌": 1.2,  # Banana (ape food)
    "🎉": 1.8,
    "🥳": 1.8,
    "😎": 1.2,
    "😊": 1.2,
    "😀": 1.0,
    "😃": 1.0,
    "🤩": 1.8,
    # Strong bearish
    "📉": -2.0,
    "💀": -2.5,
    "☠️": -2.5,
    "🪦": -2.5,
    "⚰️": -2.5,
    "😭": -2.0,
    "😢": -1.5,
    "😰": -1.5,
    "😱": -2.0,
    "🤮": -2.0,
    "🤢": -1.8,
    "👎": -1.5,
    "👇": -1.2,
    "⬇️": -1.5,
    "🔴": -1.8,
    "🐻": -2.0,  # Bear
    "🩸": -2.0,  # Blood
    "📛": -1.5,
    "❌": -1.5,
    "🚫": -1.5,
    "⚠️": -1.2,
    "😤": -1.2,
    "😡": -1.8,
    "🤬": -2.0,
    "😞": -1.5,
    "😔": -1.3,
    "😩": -1.5,
    "🥺": -1.0,
    "💩": -1.8,
    "🗑️": -1.8,
    "🤡": -1.5,  # Clown (self-deprecating loss)
    # Neutral/context-dependent
    "🤔": -0.3,
    "🧐": 0.0,
    "👀": 0.5,  # Watching, often anticipatory
    "👁️": 0.3,
    "🔍": 0.0,
    "📊": 0.0,
    "📋": 0.0,
    "🎰": 0.5,  # Gambling
    "🎲": 0.3,
    "⏰": 0.0,
    "⏳": -0.3,
}

# =============================================================================
# SLANG PHRASES (multi-word expressions)
# =============================================================================

SLANG_PHRASES: Final[dict[str, float]] = {
    # Strong bullish
    "to the moon": 3.0,
    "diamond hands": 2.5,
    "wen lambo": 2.0,
    "wen moon": 2.0,
    "this is the way": 1.5,
    "buy the dip": 2.0,
    "btfd": 2.0,
    "cant stop wont stop": 2.0,
    "can't stop won't stop": 2.0,
    "lets go": 1.5,
    "let's go": 1.5,
    "lfg": 2.0,  # Let's fucking go
    "we like the stock": 2.0,
    "moon soon": 2.0,
    "going up": 1.8,
    "all in": 1.8,
    "yolo": 1.5,
    "free money": 2.0,
    "easy money": 2.0,
    "money printer": 2.0,
    "printer go brr": 2.0,
    "calls printing": 2.5,
    "options printing": 2.5,
    "gamma squeeze": 2.3,
    "short squeeze": 2.5,
    "squeeze incoming": 2.5,
    "bullish af": 3.0,
    "super bullish": 3.0,
    "extremely bullish": 3.0,
    "very bullish": 2.8,
    # Strong bearish
    "paper hands": -1.5,
    "falling knife": -2.5,
    "catch a falling knife": -2.5,
    "catching a falling knife": -2.5,
    "dead cat bounce": -2.0,
    "going down": -1.8,
    "going to zero": -3.0,
    "rug pull": -3.5,
    "exit scam": -3.5,
    "ponzi scheme": -3.5,
    "get rekt": -3.0,
    "got rekt": -3.0,
    "getting rekt": -3.0,
    "guh moment": -3.5,
    "its over": -2.5,
    "it's over": -2.5,
    "game over": -2.5,
    "sell everything": -2.5,
    "panic sell": -2.5,
    "panic selling": -2.8,
    "bearish af": -3.0,
    "super bearish": -3.0,
    "extremely bearish": -3.0,
    "very bearish": -2.8,
    "worst case": -2.0,
    "blood in the streets": -2.5,
    "circuit breaker": -2.0,
    "trading halted": -2.0,
    # Neutral but notable
    "not financial advice": 0.0,
    "nfa": 0.0,
    "do your own research": 0.0,
    "dyor": 0.0,
    "just my opinion": 0.0,
    "in my opinion": 0.0,
    "imo": 0.0,
    "for what its worth": 0.0,
    "for what it's worth": 0.0,
    "fwiw": 0.0,
    "breaking news": 0.5,  # Slight positive (attention-grabbing)
    "just in": 0.5,
    "developing story": 0.3,
}

# =============================================================================
# TICKER DETECTION PATTERNS
# =============================================================================

# Words that look like tickers but aren't
TICKER_BLACKLIST: Final[frozenset[str]] = frozenset(
    {
        # WSB/trading slang
        "YOLO",
        "FOMO",
        "DD",
        "HODL",
        "BTFD",
        "FD",
        "ROPE",
        "MOON",
        "APE",
        "APES",
        "GAIN",
        "LOSS",
        "PUTS",
        "CALL",
        "CALLS",
        "LONG",
        "SHORT",
        "BUY",
        "SELL",
        "HOLD",
        "DIP",
        "ATH",
        "ATL",
        # Business/finance terms
        "CEO",
        "CFO",
        "CTO",
        "COO",
        "IPO",
        "ATH",
        "ATL",
        "EPS",
        "GDP",
        "SEC",
        "FDA",
        "ETF",
        "NYSE",
        "NASDAQ",
        "OTC",
        "SPAC",
        "PE",
        "PB",
        "ROI",
        "ROE",
        "ROA",
        "EBITDA",
        "GAAP",
        "DCF",
        "IV",
        "OI",
        "DTE",
        "ITM",
        "OTM",
        "ATM",
        "LEAP",
        "LEAPS",
        "RSI",
        "MACD",
        "SMA",
        "EMA",
        "VWAP",
        "TA",
        "FA",
        # Common English words
        "USA",
        "USD",
        "EUR",
        "GBP",
        "THE",
        "FOR",
        "AND",
        "ARE",
        "NOT",
        "YOU",
        "ALL",
        "CAN",
        "HAD",
        "HER",
        "WAS",
        "ONE",
        "OUR",
        "OUT",
        "HAS",
        "HIS",
        "HOW",
        "ITS",
        "MAY",
        "NEW",
        "NOW",
        "OLD",
        "SEE",
        "TWO",
        "WAY",
        "WHO",
        "BOY",
        "DID",
        "GET",
        "GOT",
        "HIM",
        "LET",
        "PUT",
        "SAY",
        "SHE",
        "TOO",
        "USE",
        "DAD",
        "MOM",
        "ANY",
        "DAY",
        "END",
        "FEW",
        "GOD",
        "JOB",
        "LAW",
        "LOT",
        "MAN",
        "MEN",
        "OWN",
        "PAY",
        "RUN",
        "SET",
        "TOP",
        "TRY",
        "WAR",
        "WHY",
        "WIN",
        "WON",
        "YES",
        "BIG",
        "FAR",
        "LOW",
        "YET",
        "PER",
        "KEY",
        "AGO",
        "ACT",
        # Internet/chat slang
        "LOL",
        "WTF",
        "OMG",
        "IMO",
        "TLDR",
        "LMAO",
        "IMHO",
        "TBH",
        "IDK",
        "SMH",
        "FYI",
        "BTW",
        "RN",
        "TIL",
        "IRL",
        "NSFW",
        "AMA",
        "ELI",
        "PSA",
        "TIL",
        "IIRC",
        "AFAIK",
        "NGL",
        "TBF",
        "JFC",
        "FFS",
        "STFU",
        "LFG",
        "GG",
        # Crypto false positives
        "DEFI",
        "NFT",
        "DAO",
        "DEX",
        "CEX",
        "KYC",
        "AML",
        "TVL",
        "APY",
        "APR",
        "LP",
        "AMM",
        "GAS",
        "WEI",
        "GWEI",
        # Countries/regions
        "USA",
        "UK",
        "EU",
        "UN",
        "NATO",
        "UAE",
        "IMF",
        # Misc
        "AI",
        "ML",
        "API",
        "SDK",
        "UI",
        "UX",
        "OS",
        "CPU",
        "GPU",
        "RAM",
        "SSD",
        "HDD",
        "LED",
        "LCD",
        "USB",
        "URL",
        "PDF",
        "FAQ",
        "TOS",
        "LLC",
        "INC",
        "LTD",
        "PLC",
        "AG",
        # More common short words that aren't tickers
        "IS",
        "IT",
        "AS",
        "AT",
        "BE",
        "BY",
        "DO",
        "GO",
        "IF",
        "IN",
        "ME",
        "MY",
        "NO",
        "OF",
        "ON",
        "OR",
        "SO",
        "TO",
        "UP",
        "US",
        "WE",
        "AM",
        "AN",
        "AX",
        "EX",
        "HI",
        "ID",
        "MA",
        "PA",
        "OK",
    }
)
